### ISSUE TITLE
Applications page

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#1]
Need a new applications page; there is an existing one from the previous site that we'd like to try and replicate
[index.html.txt](https://github.com/rhit-corridg/rc-website-web/files/8681849/index.html.txt)
.

**Comment by ActuallyGoobie** [comment]
I am working on this! If anyone else has input, lemme know.

**Comment by rhit-corridg** [comment]
https://github.com/rhit-corridg/rc-website-web/commit/0ee3680f9aa17287ae509e829bb86ec01d56997a https://github.com/rhit-corridg/rc-website-server/commit/5c97c83514cd90017fa7ad28aea3884c2f92c9f1
