### ISSUE TITLE
Add new RTS vehicle spawn locations to map

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#10]
{name = "Vinewood Hills SPAWNER", x = -656.607361, y = 904.470337, z = 227.787949, h = 356.905823}, -- Rock (81915)
{name = "Davis Spawner", x = 109.259407, y = -1818.575806, z = 25.978167, h = 227.733505}, -- Rock (81915)
{name = "Tataviam Mountains Spawner", x = 2586.522461, y = 417.764465, z = 107.971870, h = 91.226318}, -- Rock (81915)
{name = "Route 68 Spawner", x = 66.144501, y = 2783.563232, z = 57.210938, h = 142.251266}, -- Rock (81915)
{name = "Fort Zancudo", x = -1836.995117, y = 2945.035156, z = 32.148869, h = 356.558197}, -- Rock (81915)
{name = "Vespucci Spawner", x = -1022.011475, y = -1428.492188, z = 4.607001, h = 181.643707}, -- Rock (81915)
{name = "La Mesa Spawner", x = 924.564575, y = -1236.554443, z = 25.057011, h = 88.670158}, -- Rock (81915)
{name = "Docks Spawner", x = 986.366272, y = -2915.694092, z = 5.414104, h = 85.714531}, -- Rock (81915)
{name = "Docks Spawner", x = -160.033218, y = -2390.188721, z = 5.512583, h = 181.355148}, -- Rock (81915)

**Comment by rhit-corridg** [comment]
Are these car, heavy, or aviator

**Comment by YeahItsRock** [comment]
Car

**Comment by rhit-corridg** [comment]
Fixed in commit https://github.com/rhit-corridg/rc-website-web/commit/56521b7ba77a59e7583ab40485328b1c144d19c1
