### ISSUE TITLE
cfx.re links break pretty often

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#13]
consider replacing cfx.re links, or adding an alternative that points to server.tycoon.community:30120+30121

**Comment by rhit-corridg** [comment]
This is going to be part of a larger issue. I need to move passwords out of a config file and into the .env file before anyone else can work on this issue

**Comment by rhit-corridg** [comment]
> This is going to be part of a larger issue. I need to move passwords out of a config file and into the .env file before anyone else can work on this issue

Handled in https://github.com/rhit-corridg/rc-website-web/commit/a171ad59664832d35242a4b6f914f54656de0ccb

This can now be handled. File that needs changing is in rc-website-server, [app_configs.js](https://github.com/rhit-corridg/rc-website-server/blob/master/app/configs/app_configs.js)

**Comment by PuckishRogue91** [comment]
Do you also want to clear out the inactive servers in that list?

**Comment by YeahItsRock** [comment]
Sounds good!

**Comment by PuckishRogue91** [comment]
Are you wanting the links to be changed or are you wanting to add new links as alternatives?

**Comment by YeahItsRock** [comment]
I like the idea of making the two server.tycoon links first in the list, and keep the cfx.re links as backups if it's all the same

**Comment by PuckishRogue91** [comment]
Pushed a fix.
