### ISSUE TITLE
Payout for RTS combines numbers into a string

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#17]
https://www.rockwelltransport.com/home/dashboard/payout

When the user enters numbers for the three types of vouchers, the resulting number is a string. For example, 1+1+1=111 instead of 3.

**Comment by rhit-corridg** [comment]
This is handled in [PayoutContainer.js](https://github.com/rhit-corridg/rc-website-web/blob/master/src/components/Dashboard/Payout/managers/PayoutContainer.js)

**Comment by rhit-corridg** [comment]
Working on it

**Comment by rhit-corridg** [comment]
Fixed in https://github.com/rhit-corridg/rc-website-web/commit/7671da505bb9b347c63037ee4955459d2caec043
