### ISSUE TITLE
Visiting rockwelltransport.com sometimes redirects to Discord login erroneously

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#2]
www.rockwelltransport.com, www.rockwelltransport.com/PIGS.html, and www.rockwelltransport.com/RTS.html should not require Discord logins

**Comment by rhit-corridg** [comment]
I cant recreate this issue

**Comment by PuckishRogue91** [comment]
I haven't been able to recreate it either.

**Comment by YeahItsRock** [comment]
I'll see if I can find reliable replication steps

**Comment by YeahItsRock** [comment]
Have not been able to replicate; will reopen if it comes up again.
