### ISSUE TITLE
Search Manager Payouts table in CEO view - Sort by date sorts alphabetically

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#25]
https://www.rockwelltransport.com/home/dashboard/payout/

When sorting by date in CEO's Search Manager Payouts table, the column gets sorted alphabetically by the day, rather than chronological order

Date format is 'Fri May 13 2022'

**Comment by rhit-corridg** [comment]
Fixed in https://github.com/rhit-corridg/rc-website-web/commit/f314e1928545a7d7475f129d26a434830e72c625
