### ISSUE TITLE
Clicking the RC logo in the top-left of the homepage goes nowhere

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#29]
Clicking the RC logo on certain pages sends the user to https://www.rockwelltransport.com/index.html, which is blank.

Affected pages
- https://www.rockwelltransport.com/home.html
- https://www.rockwelltransport.com/PIGS.html
- https://www.rockwelltransport.com/RTS.html

Recommendation
- Send the user to: https://www.rockwelltransport.com/home.html

**Comment by PuckishRogue91** [comment]
Submitted a push request for this.
