### ISSUE TITLE
Modify the /home/ttools homepage to let everyone access the search bar

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#30]
https://www.rockwelltransport.com/home/ttools/

This request is asking that the search bar become available to anyone

**Comment by rhit-corridg** [comment]
Fixed in https://github.com/rhit-corridg/rc-website-server/commit/1b9de114a35177dd9f03493813755ea6ff4f1b50 and https://github.com/rhit-corridg/rc-website-web/commit/980a290f6a49a7cf083f50bfcd8ffaf702748087
