### ISSUE TITLE
Modify search bar in /home/ttools to also recognize Discord ID

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#31]
https://www.rockwelltransport.com/home/ttools/

Change search bar in TTools so that it recognizes both Discord ID and in-game ID

**Comment by rhit-corridg** [comment]
https://github.com/rhit-corridg/rc-website-web/commit/a600b80ada663c220d8cd921053066f406de3e7a and https://github.com/rhit-corridg/rc-website-server/commit/aa2dc787ec3628bf24009109b838af85f9cca767
