### ISSUE TITLE
Add backpack storage to /home/ttools

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#32]
https://www.rockwelltransport.com/home/ttools/

Add backpack storage to /home/ttools

Allow the user to toggle results by Inventory/Backpack/Both

**Comment by rhit-corridg** [comment]
https://github.com/rhit-corridg/rc-website-web/commit/5f8e110615149fdd87e7addda6f5b12718e06ffd and https://github.com/rhit-corridg/rc-website-server/commit/07745ff24737c878567d427e15e0bbb0038d5007
