### ISSUE TITLE
Add new trainyard to /home/ttools/biz/

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#33]
Add Palmer-Taylor business to https://www.rockwelltransport.com/home/ttools/biz/

This new business should be treated as a trainyard

**Comment by rhit-corridg** [comment]
There's a url that gets us tycoon businesses correct? I need more info on the business

**Comment by YeahItsRock** [comment]
http://server.tycoon.community:30120/status/config/omni_businesses

Does that still work?

**Comment by rhit-corridg** [comment]
https://github.com/rhit-corridg/rc-website-web/commit/b18c17cca7903d176803f0ec2fa84340c436e8ee
