### ISSUE TITLE
Hunger and thirst should be removed from /home/ttools

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#34]
https://www.rockwelltransport.com/home/ttools/

Hunger and thirst were yeeted from Tycoon, lets yeet them too!

(Probably just comment them out tho cuz TT sometimes changes their mind)

**Comment by rhit-corridg** [comment]
Fixed in commit https://github.com/rhit-corridg/rc-website-web/commit/37f226a73e31c357f6c5ca76ccf3016bfdfc2768
