### ISSUE TITLE
'Your payouts' table in the Profile page sorts dates alphabetically by day

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#37]
https://www.rockwelltransport.com/home/profile

"Your payouts" table; there is an issue where dates are sorting alphabetically by the day.
Format: Wed June 19 2019; this is sorting Wednesdays as last and Fridays as first.

**Comment by rhit-corridg** [comment]
https://github.com/rhit-corridg/rc-website-web/commit/38b9426f5c6922f86fcf5cf9e510073305cb6271
