### ISSUE TITLE
Update Server Status Page

### ISSUE THREAD

**Issue by PuckishRogue91** [rhit-corridg/rc-website-web#39]
It would appear that the cfx.re link breaks extends to the server status page, so I'm going to need adjust that page as well.  
So:
server.tycoon.community:30120
server.tycoon.community:30121

Do we know if :30122 is the event server?

**Comment by rhit-corridg** [comment]
I'm not sure, @YeahItsRock do you know?

**Comment by YeahItsRock** [comment]
I do not know and it's not usually online. I'd just keep the cfx.re link for the event server
