### ISSUE TITLE
'Active' button in "Managers Cashouts" table filters all instead of just active

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#4]
[https://www.rockwelltransport.com/home/dashboard/company/]

Active toggle in Managers Cashouts table on [https://www.rockwelltransport.com/home/dashboard/company/] page filters ALL entries, instead of only showing managers that are marked Active in the DB

**Comment by rhit-corridg** [comment]
This has been fixed in commit https://github.com/rhit-corridg/rc-website-web/commit/a7b903ffeb68e53999b2c9953493a27f54d47c68
