### ISSUE TITLE
Potential home/ttools XP Bonuses Issue

### ISSUE THREAD

**Issue by PuckishRogue91** [rhit-corridg/rc-website-web#41]
In reviewing the xp bonuses on the ttools page, I noticed that I do not show up as having the premium XP despite having a current Premium license.
![ID](https://user-images.githubusercontent.com/105464888/168444742-bc826651-0dee-40c6-812d-90588329a46e.jpg)
![Site](https://user-images.githubusercontent.com/105464888/168444744-5c912802-d0c8-4144-865d-cb2a1de1f22f.jpg)

I compared notes with Luzak and it seems to correctly reflect his status:
![L1](https://user-images.githubusercontent.com/105464888/168444770-32f66627-f291-4924-9884-7f458d09c962.jpg)
![L2](https://user-images.githubusercontent.com/105464888/168444788-283f143f-b4b9-4892-bee0-15bd35773c6b.jpg)

From the code I saw, it's a pretty cut and dry yes/no query, so I'm not entirely sure it's on us. But I'm not sure where else to check premium XP status to see if I show up differently.

**Comment by rhit-corridg** [comment]
I'm not sure how to tell from the data response that someone has premium. If someone could ask someone who may know that would be super helpful
