### ISSUE TITLE
Applications fail when users enter emojis in the nickname field

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#47]
The only error that we can see regarding the app looks like this: FAILED APPLICATION 598986 <@undefined>

Resolutions:

- Make the error more specific, so we can complain at people to take the emojis out of their name
OR
- Only allow alphanumeric values in the name field

**Comment by rhit-corridg** [comment]
I don't think this is an issue with emojis

**Comment by rhit-corridg** [comment]
https://github.com/rhit-corridg/rc-website-web/commit/84a6b9e81361acf11741ba2e731cacd0872fd2bb and https://github.com/rhit-corridg/rc-website-server/commit/f20a28f0ae75fc52145ecd4e9e5428bbc4b50fbe
