### ISSUE TITLE
Add Manual Hire to Website

### ISSUE THREAD

**Issue by 100xdonaldx001** [rhit-corridg/rc-website-web#48]
Just add maybe to the Applicants page a way to manually hire people too.
Just as an alternative to Alfred

**Comment by rhit-corridg** [comment]
I'm not too sure about this one. The only reason Alfred has a hire command is to hire applicants, not really meant for manual hiring. 

I feel like people should have to fill out an application

**Comment by rhit-corridg** [comment]
Stale
