### ISSUE TITLE
"Manager" status toggle is not working in CEO view

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#5]
https://www.rockwelltransport.com/home/dashboard/company/
Company Members table
CEO has 4 buttons for each entry; Manager/RTS/PIGS/Yeeted
When someone is a Manager, the CEO presses RTS/PIGS/Yeeted to remove manager status
It is not currently working; pressing RTS/PIGS changes their company, but does not remove the Manager status, which should also remove their 'Active' status in the DB

Clicking "Manager" on someone also does not give them Manager permissions on the site; suspect this is a related issue

**Comment by rhit-corridg** [comment]
This is handled in [CompanySelector.js](https://github.com/rhit-corridg/rc-website-web/blob/master/src/components/Dashboard/Management/CompanyMemberButtons/CompanySelector.js)

**Comment by PuckishRogue91** [comment]
Looking at this, the button looks like it is intended to toggle manager status, but it is disabled if they are already a manager. Is it intended to forcibly remove manager status if their company is changed, or should this button be enabled regardless of if they are already a manager?

**Comment by YeahItsRock** [comment]
I like the second option a bit better if that's not difficult. Maybe it's always active, and turns a different color if they're a manager? Maybe green or something?

The way it used to work was the that it forcibly removed the manager status if their company changed.

**Comment by PuckishRogue91** [comment]
Okay, I'll take a look at this.

**Comment by rhit-corridg** [comment]
Cannot recreate clicking manager not giving manager perms
