### ISSUE TITLE
Get Top Turnins on the management page seems to ignore date range

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#58]
https://www.rockwelltransport.com/home/dashboard/company

Get Top Turnins table seems to retrieve highest amount of vouchers of all time, rather than from a specific date range

**Comment by rhit-corridg** [comment]
https://github.com/rhit-corridg/rc-website-server/commit/c170e837aff48b0fa2d1812dc250fff47a63872e
