### ISSUE TITLE
Completionist Page doesnt work on S2

### ISSUE THREAD

**Issue by 100xdonaldx001** [rhit-corridg/rc-website-web#68]
The completionist page still doesnt work on S2 

Console errors:
WebSocket connection to 'wss://www.rockwelltransport.com/sockjs-node/905/e3uud0zc/websocket' failed  websocket.js:7
GET https://www.rockwelltransport.com/api/tycoon/currentvehicles 400 (Bad Request)  makeApiRequest.js:14
Uncaught (in promise) {error: 'Tycoon Servers Offline'}   completionist:1

Further informations:
https://discord.com/channels/447157938390433792/974001951358459944/986309579065405540
https://discord.com/channels/447157938390433792/974001951358459944/983650046618779698
https://discord.com/channels/447157938390433792/974001951358459944/983750276748021811
https://discord.com/channels/447157938390433792/974001951358459944/984493176091971724

**Comment by TheGamerzs** [comment]
Seems to have been fixed.
