### ISSUE TITLE
CEO permission does not show a search bar to check other users' businesses

### ISSUE THREAD

**Issue by YeahItsRock** [rhit-corridg/rc-website-web#7]
https://www.rockwelltransport.com/home/ttools/biz/

CEO permission does not show a search bar to check other users' businesses; not sure if this is also an issue for other perm levels

**Comment by rhit-corridg** [comment]
This is handled in [BizHomeScreen.js](https://github.com/rhit-corridg/rc-website-web/blob/master/src/components/TTools/Biz/BizHomeScreen.js)

**Comment by rhit-corridg** [comment]
https://github.com/rhit-corridg/rc-website-web/commit/62043ca047d658239e950e1d76ae7098591dfe48
